# Generated by Django 5.1.1 on 2024-09-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_about_sociallink"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
        migrations.DeleteModel(
            name="SocialLink",
        ),
    ]
